# -*- mode: org -*-
# Last modified: <2013-02-07 14:52:51 Thursday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   BD's分类需求
#+AUTHOR: Richard Wong

和BD交流的内容见最下FaQ。
* 暂时是这个样子，之后会主要是领域知识和具体实现的方法。

* 已经讨论得到的可能需要被分类的类型。
  1. 新闻
  2. 论坛
  3. 博客
  4. 微博
  5. 电子报
  6. 视频
  其中 新闻，论坛，博客，电子报，为全网抓取。
  微博分为腾讯微博和新浪微博。

* 顾问分类定义（我自己总结的一套，会与顾问的有出入）
  主要是通过人工判断，将内容分类
  | 内容分类 |
  |----------|
  | 广告     |
  | 价格     |
  | 教学视频 |
  | 品牌     |
  | 其他     |
  | 设计     |
  | 生活     |
  | 网购分享 |
  | 线上互动 |
  | 消费体验 |
  | 营销反馈 |
  | 营销互动 |
  | 在线互动 |
  | 质量     |
  | UCG      |
  事实上，UCG还会被分为好几种。
  考虑到svm的特性，并不是所有的微博分类对分词之后的特征都有良好的效果
  反馈。
  顾问所分类的文本为硬分类，但经过仔细讨论，分类之间的关系并不是一定硬
  分类，我现在实现的是硬分类，具体那些分类是互斥，那些是包容的，需要进
  一步讨论。(这里考虑到可能会过度实现，所以先rusty一个简单的)

* 全网分类
  全网在顾问提供的文本串中只是有一小句话而已。因为一直在做的就是腾讯和
  新浪weibo的内容。还需要交流以下几个问题：
  1. 判断全网分类的标准是否就是一来那一小串文本？
  2. 一般全网具体的来源。
  3. 更多的全网的领域知识。（你们怎么判断的，工作流程之类）
  4. 全网分类包含：
     | 产品     |
     | 广告     |
     | 价格     |
     | 品牌     |
     | 其他     |
     | 设计     |
     | 生活     |
     | 消费体验 |
     | 新闻     |
     | 营销反馈 |
     | 质量     |

* 分类领域方法。
  无。
  现在分类完全依靠ML的方法(svm)来处理分类。
  这些需要再来总结和顾问进行更深层次的研究。

* 几个对话片段。(节选)
  其中R代表我。BD代表顾问。
** R: 你们如何判断这个weibo是否是产品还是广告的？
   BD: 我们也不是很清楚怎么判断的，大部分都是人工吧，人为经验判断最重
   要。
   R: 这样，你们有没有专门判断的方法？就是具体判断的规则？
   BD: 哦，这样啊，我们都是人工的，没有什么非常具体的方法。
   R: 恩，那我先看看，总结出一些规则，然后再跟你们进行下一步的讨论吧。
   conclusion: 还是需要进一步讨论，先作出通用的方法，领域知识系统之后建立。

** R: 文件为啥都是以hat----> ^ 开头的？
   BD: 什么意思？
   R: 我想问下文件名的格式有什么深入的含义。。
   BD: 不知道, 你可以随便玩弄.
   conclusion: 文件名自己设计吧。

** BD: 我需要整成什么格式发给你吗？还是直接给你自己搞啊？
   R: 你先给我看一下吧。我看看大致什么样子。
   BD: 先给你一个看看吧.我这里文件太多了
   conclusion: 看过文件，之后发现文件格式需要先对BD有要求，这点已经处
   理完毕。

** BD: 真希望这个东西早点造出来，人工去噪这件事太可怕了.
   R: 什么是噪声？
   BD: 怎么说呢？广告贴什么的都算噪音.
   R: 你怎么判断是噪声。
   BD: 去噪音这个过程需要一直积累经验, 不断放到词库里面去.
   BD: 留下的需要的信息是能找出消费者反馈的信息。
   R: 有一些类是噪声，有一些是用户需要的。对吧。
   BD: 嗯。
   BD: 然后用户需要的这些,你还能分类吗?
   R: 能。(只是不知道效果怎么样而已。。。。)

** R: 你的工作流程大概？
   BD: 我的工作流程是这样的，拿到原始数据之后，先去噪音，就是你弄好的
   那个东西.
   BD: 第二步, 把去噪之后的内容分类。
   BD: 判断正负面中性混合什么的.
   R: 还需要你们人工判断么？
   BD: 如果你们能整合到一起就最好了，不然我们就让他们手动跑。
   R: 哦。这是可以的。调用的一样是hehe的api.
   conclusion: 和hehe讨论一下，再看看是否应该吧api用进来。

** R: 你们对出错是怎么处理的？
   BD: 出错很正常。顾问可能一天都盯着这个东西。
   R: 不去纠正什么的？
   BD: 不会的，只能说尽量不去分错这些东西。
   conclusion: 模型容错性非常重要。

** BD: 其实现在BD有很多在做的项目,都是人工分类的, 快消行业很多..blahblahblah...
   R: 你说我设计一个结构，人工分类处理几百条（要求抽样均匀的），然后机
   器就可以自动学习分类，有用没？
   BD: 有, 会是实时吗.
   R: 瞬间出结果？实时指的哪种实时。
   BD: 不需要回家机器学习个一两天的。
   R: 好吧，根据任务量，1w条, 大概1个小时也有可能，能接受么？（按现在的
   速度）
   BD: 没有问题。
   conclusion: 设计一个通用的分类方法。（现在已经实现）

** R: 如果明年继续处理，会继续这些品牌的分类，还是新的？还是都有？（现在要设计是否要固化上去）
   BD: 都有,还会有新的.
   conclusion: 同时提供优化过的分类方法和通用的分类方法。（准确率还是
   提高非常明显的）

* 跟BDs讨论，发现主要有这几个问题。
1. 很多时间都在手工处理很多费力的问题。
2. 人工可能出现很多问题，但是一般都会忽略。
3. 问题本来就定义不是非常的清晰。（缺少产品的定义）
