# -*- mode: org -*-
# Last modified: <2012-12-04 19:03:58 Tuesday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   Lda Report
#+AUTHOR: Richard Wong

* Report <2012-12-04 Tue>

** LDA experiment 1:

*** LDA parameters:
    alpha=6.250000
    beta=0.100000
    ntopics=8
    ndocs=1899
    nwords=203940
    liter=2000
*** each categories top word here:
    Topic 0
    用户 产品 营销 企业 广告 蜂窝 市场 网络 媒体 品牌 互联网 移动 发展 视频 网站 需求 价值 时间 行业 数据 查看 手机 技术 模式 信息 平台 社交 时代 未来 提供 百度 内容 已 美国 电商 旅游 设计 研究 搜索 消费者 员工 系统 目前 创业 全球 文化 客户 重要 发布 应用 纸箱 微软 苹果 纸板 纸护角 高 创新 推出 传统 互动 销售 英国 管理 社会化 团队 报告 经济 国内 创意 提升 传播 新浪 经验 京东 宣布 称 显示 msn 价格 运营 方式 现场 功能 包括 体验 影响 目标 推广 在线 第一 科技 购买 分析 利用 腾讯 超过 情况 网 相关 投资
    Topic 1
    吃 泪 真的 想 偷笑 挖 买 感觉 喜欢 笑 鼓掌 鼻屎 真是 怒 死 求 开心 可爱 汗 完 抓狂 快 不错 逼 是不是 威武 话 真心 回家 可怜 这是 衰 花心 围观 尼玛 睡 找 蛋糕 屌 江南 睡觉 最右 酷 带 走 晕 good 听 希望 第一次 声音 男人 小时 猫 馋嘴 奥特曼 赞 哭 时间 style 吃惊 兔子 喝 木有 害羞 帮 穿 前 男 傻 生病 效果 挺 懂 擦 吃饭 黑 女 衣服 吐 好吃 照片 上班 还好 回去 女人 妹子 妈妈 妹 妈 ps 感动 不好 刚 搞 喵 笑哈哈 斤 孩子 老师
    Topic 2
    想 这是 却 孩子 走 老师 事 人生 听 日本 喜欢 前 问 国家 才能 钱 话 写 重要 所有 希望 故事 社会 电影 岁 人民 逼 相信 明白 美国 找 生命 不了 总 历史 告诉 小时 学生 真是 人类 先 讲 不好 总是 认为 所谓 努力 字 时间 改变 钓鱼岛 决定 政府 学校 精神 学习 意义 懂 方式 思考 苹果 死 存在 一条 值得 已 经历 领导 科学 原因 医生 真的 理解 关系 习惯 现实 大学 失败 自然 愿意 接受 面对 蜡烛 青年 代表 影响 根本 书 真实 第一 男人 挺 父母 个人 放 态度 至少 当年 少 老板
    Topic 3
    写 推荐 不错 技术 学习 数学 语言 代码 pdf 开发 方法 设计 系统 职位 阅读 目前 数据 qq 应用 测试 文章 认识 科幻 搞 版本 专业 感觉 帮忙 环境 书 文件 发布 网站 游戏 云 本书 时间 老师 翻译 python 打算 身边 项目 管理 几个 社区 程序员 内容 高兴 演讲 工具 程序 分析 工程师 软件 产品 介绍 google c 薪资 编程 媒体 这是 国内 计算 淘宝 买 开源 换个 信息 理解 完 视频 博客 解决 情况 r 作者 团队 讲 想 更好 值得 it 下载 java 简单 版 性能 研究 论文 猎头 兴趣 所有 适合 算法 逻辑 网易 大会 匹配
    Topic 4
    给力 期待 空间 手机 希望 好运 免费 电脑 试试 签到 云 指数 存储 奖品 加油 无限 旗下 下载 品牌 中奖 新浪网 同步 手气 超大 粉丝 数据 努力 颗星 武汉 资源 海量 祝福 c 晒 一盘 照片 收获 来看 时尚 礼物 参加 存储空间 爆发 微力 幸运 人手 时间 机 耶 美好 晚 张 拍 葡萄酒 精彩 快 经典 最佳 双十 年度 不错 奖 人品 惊喜 温馨 风景 博主 付出 有奖 江城 全球 现场 大大 激动 参与 微风 微盘 体验微盘 mini 宣传 心情 辛苦 脱光 酒店 双 闪 之恋 rp 简单 广场 热情 春天 有木 威武 住 京东 热门+1 漫画 多多 天空
    Topic 5
    手机 版 体验 删除 更新 此微 如需 博已 帮助抱歉 客户端 好友 http 升级 微 新增 推荐 下载 勋章 全新 投票 新浪 点击 com 免费 weibo 想 cn 功能 图片 参与 会员 不错 领取 抢 新版 投给 主题 发布 小米 求 sinaurl android 赢 链接 选项 抽奖 地址 已 精彩 发起 二维码 文件 评论 天下 个性 表情 明星 登录 夏日 网 热门 找 iphone5 无需 v5 ipad 亲 专属 喜欢 来看 测试 快去 视频 聊天 注册 iphone 刷 游戏 hold 界面 浏览 浏览器 话费 秋季 收藏 内置 秒杀 博达 即可 照片 网页 号 粉丝 台 z v2 鲜 现金 语音 摇
    Topic 6
    喜欢 幸福 爱情 想 却 梦想 城市 真的 快乐 参加 大乐 感觉 斗 游戏 时间 女人 人生 希望 男人 美丽 买 坚持 事 给力 赢 心情 成就 努力 挑战 温暖 分 妈妈 总是 拥有 光棍节 健康 刚刚 肌肤 超级 宝宝 错过 找 级 好友 时刻 生命 轻松 秀 珍惜 成长 黄金 期待 快 冠军 走 电影 开心 农场 加油 道具 美食 美 童鞋 变 出 简单 不错 越 寂寞 梦 ta 完美 忘记 身边 nbsp 星座 漂亮 美女 行动 使 命运 旅行 穿 微笑 更有 相信 便 欢乐 未来 乐 身体 穿越 惊喜 升级 安全 十分 高 英雄 皮肤 阳光
    Topic 7
    個 音乐 歌曲 唱 唔 還 愛 時 专辑 沒 為 過 快 i 视频 老 单曲 网 豆瓣 點 發 赞 國 面 火爆 現 美剧 後 抽取 这张 地址 已有 開 大奖 樣 死 试听 無 系 参与 給 一首 fm 謝 d mv 實 家 日月 机器人 成 角色 真是 播出 感 轉 公布 衰 e 计划 作品 相 嗎 行 好听 學 实物 内测 真爱 然 話 全国 麽 随手 开放 击败 噢 私人 當 機 真的 動 三国 於 剑 情 明教 高 歌 预告 明白 地球 虾米 明尊 抓狂 开启 場 間 經 快乐

*** python translation code:
    #+begin_src python

    #+end_src



** conclusion
*** 繁体字
    现在有一部分微薄都是用的繁体字，繁体字对于LDA的影响非常明显，体现
    在两个方面：
    1. jieba分词对于繁体字支持不好，算法并未考虑繁体字，分出来的都是单字。
    2. 繁体字和简体字本来就有很大程度上的意思对接关系，只有少部分繁体
       字是特别的词和词义。比如:
       头发发展 -> 頭髮發展
       萝卜卜卦 -> 蘿蔔卜卦
       秒表表达 -> 秒錶表達
       晾干乾坤 -> 晾乾乾坤
    我给出方案是，加上繁体词词库，然后再用jieba分词，然后转回简体字。

    我给出方案是，繁体词逆向匹配转成简体字，参考下面ref，

    当然更好的办法必然是加上繁体词词库，然后再用jieba分词，最后根据词转
    回简体字。可以具备更高的准确率，但是设计繁体词词库非常复杂，而且分词
    的不确定性更明显。我们需要一个具备有(pos pinyin freq word)四元组组成
    的牛逼的词库就可以尽可能大的提高分词质量和效果。对于市面上的任何一种
    分词都会有加成作用。(只要开源)

*** 应该添加的停用词库
    停用词在分类中的特点应该是：
    普遍性，不具有语意，分类场景不明确。
    话说我匹配出来的连接，但是还是有里面的东西。

*** ref
    http://svn.wikimedia.org/svnroot/mediawiki/trunk/phase3/includes/ZhConversion.php
    demo code:
    #+begin_src python

    #+end_src
