# -*- mode: org -*-
# Last modified: <2013-05-04 17:47:18 Saturday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   4days in a week
#+AUTHOR: Richard Wong

* 从日渐增高的体重说起
  最近体重上升特别快, 很快就突破了90kg(200lbs), 180斤是我能够承受的底线.
  如果到了180, 那么就是时候去减低到一个可承受的范围.

  如果说保持天天锻炼, 那么我是不太可能到我的理想体重的, 经常锻炼, 吃饭
  的时候尽量避免高热量的食物, 谁都知道. 但是为什么还没有行动呢?

  无法坚持才是最重要的问题.

** 因为缺乏恒心
   每个人想要做到一些什么, 做起来总是用不上力气.
   在北京我就经常坚持不下去做计划好的事情, 以至于之后的几个月连计划都
   懒得制定了.
   有模糊不清到了浑浑噩噩, 很快就2013年了. 似乎感觉是不是2013年马上就
   要过去了.
   好多人给我说, 你从西藏回来没什么区别啊. 今天我再次审视这个问题, 其
   实还是有很大区别的, 因为会更相信自己, 相信自己可以能克服各种各样的
   困难.
   话说回来, 你真的相信你自己么? 你凭什么相信你自己的, 就因为你是你自
   己么? 你真的能够控制自己的行为么?
   自信可是不是盲目的相信自己就可以搞定的事情.
   不管如何, 那为什么减肥这个事情我坚持不下去呢?

** 需要一个目标
   为了解决坚持做一件事情的方法, 那就是给自己一定的奖励, 无论是金钱上
   的, 精神上的, 都可以.

   我给自己定下了一个目标, *马拉松*, 具体一点, 2013年的厦门马拉松全马.
   虽然很多人挂掉, 但是我相信我不会, 而且可以跑完全程.

* 为什么是马拉松?
  跑马拉松是一个长期的工作, 可能会有很多人从来没有准备过就可以上场开跑,
  但那是玩命.
  很多领域都有自己的特点. 马拉松也是一样.
  一个专业的选手和一个普通的选手是有显著不同的, 但这我们无需关心, 我也
  不太认为我这辈子的目标可能会有马拉松获得冠军的想法.
  但是, 一个有体系化训练方法的选手和一个单纯靠生猛去做的选手结果也是有
  显著不同的.

** 我对于专业的理解.
   我现在认为最恐怖的并不是别人比你更牛逼, 而是在同样的辛苦的学习下,
   她跟你学习的一样的东西, 但是偏偏学得更多. 你一样辛苦付出, 却没有获
   得应有的回报.

   于是我要专业起来,

** 训练马拉松需要的注意事项.
   - 每周锻炼不能少于三次, 不能多于五次
     专业的教练告诉我们, 4次最合理, 跑多并不会为你的耐力带来任何好处.
   - 每周的锻炼规律是, 短距离1天, 中距离1天, 短距离1天, 长距离1天.
   - 虽然每周锻炼4次, 但是不能连续休息三天, 应该在工作量最大的一天前后
     休息一天.
   - 在开始跑步的时候, 跑慢一点.
   - 控制自己能跑完每天的计划, 而且即使有体力的情况也不超跑.
   - 下周的跑步总长度不应该多于本周的10%, 否则很容易受伤.
   - 鞋子是决定你受不受伤的关键因素, 拥有一双适合自己脚型的鞋子至关重要.
     鞋子应该大平时的半码, 因为你在运动的时候, 脚会膨胀半码.
   - 跑步训练中并没有时间限制. 所以当认为你身体不足以支撑你继续跑下去
     的时候, 走一会. 因为你可能跑快了.
     你需要做的并不是在时间区间内跑完全程, 而只是跑完全程.
   - 跑步的准备运动也特别重要.
   - 小心你的衣服, 乳头会因为衣服材质磨出血, 大腿内侧也会磨掉皮乃至出血.
   - 在正式的马拉松训练前, 应该有充足的准备计划, 使得你的体质可以跟上
     正式训练的代价.

** 马拉松和我
   所以这将会是一个长线的过程.
   在五月将会准备马拉松的活动. 6-10月将会是正式的马拉松训练计划. 以及
   最后为期2个月的保持计划来迎接厦马.
   其实马拉松也就是才开始而已. 希望我在坚持跑完了厦马的时候去说之后的
   话吧.

* 没有银弹
  马拉松有一个特别有趣的点, 就是最合适马拉松的温度是10-12度. 少于5度和
  多余15度都不适合跑马拉松.
  想起来最适合人体最适应的温度是24-28度, 但是睡眠的时候是18-22度.
