# -*- mode: org -*-
# Last modified: <2013-05-31 23:13:44 Friday by wongrichard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   A_Talk_With_cc
#+AUTHOR: Richard Wong

* Future
  未来的生活需要靠我们的双手去创造，
  你想要什么样的生活，就需要什么样的行动和态度。

* happy
  我觉着我这辈子最幸运的是，我们希望彼此都幸福，我的家人，我的爱人。
  我们虽渴望幸福快乐，但是我们知道这却不是有拥有很多财富。
  有财富固然好，但是并不一定会带来幸福，我并没有很多财富，所以我无法理
  解财富到底能给我带来多少快感。
  郭美美的卡可以刷出余额61亿。这个世界上没有多少人可以刷出这个数字，我
  这辈子如果不把钱换成京巴布韦币估计也很难赚到这么多钱。但是这又如何？
  难道这个世界除了郭美美没有别人幸福吗？试想，郭美美的浅薄，会在她眼角
  升起皱纹的时候继续延续吗？
  如果真的幸福和金钱可以如此转化的话，那么岂不是赚钱更多的人更有幸福感？
  只有极少数有钱人幸福？难道这个世界还有一个财富阈值来决定多少人幸福？
  盖茨在哈弗的演讲上说，希望这个世界不要只是因为首富而记住他的名字，不
  要因为PC做出的贡献就记住他，希望可以在给解决南非疾病和健康少少的帮助
  而记住他。这虽然感觉是求的名声，但是这是一种升华。他可以跟oracle的董
  事长一样奢华。他完全没有必要做这些事情。这是对自由的坚持，你知道什么
  是自由，坚持南非的贫困人民享有健康和救助的自由。
  国内的大学很少能给人一种需要低头认真思考的态度，大部分时候我们只有两
  种状态，要么无比自卑，要么高傲到无以复加。
  其实人的一生别人给不了我们什么，需要自己建立一个精神丰碑。学习且进步，
  开心又快乐的生活。
  幸福和事业有多少关系？
  无数人跳出了金笼子，又进了权笼子。
  事业成功确实会给一个人带来极大的满足感，但也基本上跟幸福关系也有限。
  甚至也不是事业有多成功，事业成功家庭幸福，固然最好，但是我们知道这确
  实难以达到。你希望一个什么样的职业生涯？然后你有一个目标，完成了这些，
  你就幸福了么？而你只能获得满足感。在获得满足感之后，随着而来的是空落
  落的人生，谁与你共享这一切？你年迈的老母？还是或许已经不在人世的祖母？
  不要等到失去才知道珍惜。
  
* corners
  无论发生什么重大影响你生活的事情，一旦意识到转折点，那就真的应该着手
  为将来做打算了，无论是哪种情况，都会得到有用的信息，知道了想知道的事
  情。
  看起来对我们不利的转折点在初期出现的时候很难让人接受，他们总是暗藏杀
  机，总感觉它们会在背后咬我们一口。它们总是让人措手不及。但是却并不能
  回避这些东西，正如这封邮件便可能是你的转折点。
  大部分错失机会的原因，正式因为我们没有对出现的转折点做出哪怕一丁点的
  回应。麻木不仁，只能失败。

* value
  生活有没有价值？
  不应该可以定义什么是价值，你的价值应该是你精神的一种，或者说是你的寄
  托，你自己的tattoo，而不应是从他人那里不加思考就汲取来的。

* plan
  首先，更改weibo的密码。我帮你更改，你帮我更改，晚上回家抽一个时间统
  一看，平时不准上微博。
  由于我们公司用qq发信息，所以没办法完全禁用qq，或者你提供一个qq的方案。
  咱们一定都控制起来，坚持1个月，然后看情况继续下一步，这便又是好的转
  折点。
  以后每个月都提议，养成一个新的好习惯，一起坚持，一起鼓励。输的一起惩
  罚，赢了一起奖励，我知道我有的时候特别喜欢自己做事情，不带你，因为我
  自己坚持都已经不易，所以我希望你的一个转变就是，跟我一起进步。

