# -*- mode: org -*-
# Last modified: <2013-05-31 17:47:03 Friday by wongrichard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   finding_job_in_2013
#+AUTHOR: Richard Wong

* 题引
  今年是史上“大学毕业生最难就业年”或者是将出现“史上最难就业季”，看来已成
  共识。这在媒体上，社会上已成流行语。一、二号国家首脑人物，也在谈大学生
  就业问题。最近的报道说，应届大学毕业生，广东的找到工作的刚过一半，北京
  的才三成多。今天的党报上还说到，有农村孩子眼见大学生找工作不易，决定放
  弃高考，说：“上四年大学，一年得花两万多，到头来工作还是不好找，不如现
  在出去打工。”而类似这样的农村临考想放弃的学生还不少。
* 为什么？
  中国号称世界最大的代工厂，但是其实都是加工型企业。需要的并不是大学生。
  大学生也不愿意去干这个。中国大学发展并没有走两条线，本科教育和技工教
  育根本不平衡，中国的技工教育基本都是考不上高中或者考不上大学的人去读
  的，而且根本没几个人心思在学习上，培养不出工业界的高级人才，这个现状
  不仅制约了中国的工业水平的发展，也影响了中国大学生的就业问题。

  再就是大学专业设置的问题。很多专业，除非是一类大学，其他学校的学生学
  了基本是不可能找到相关专业的工作的。因为需求本身就很小，而且还只有国
  家科研机构，高校教育机构才能吸收，这些机构一般对都是择优少量录取。很
  多大学为了产业发展，忽视了将来的就业问题，大肆扩招，造成了供需矛盾。

* 创业。
  之前，我也思考过，鼓励大学生创业能否作为解决其就业问题的一个选项。但
  是，无论是雷军还是刘强东这样的强人，他们的大学生创业史都以失败而告终。
  很多年轻的创业者其实都没有商业经营的基因，需要向市场交学费，这种学费
  远远比大学教育费更高。
  我觉着，如果没有真正合适的idea，特别不适合创业，是的，因为成本太高，
  你完全不知道什么是市场。我见过一些比较懂市场的，你听他们讲市场，完全
  不一样，你就可以遇见很多人，会直接摔倒，甚至陷入沼泽里面。

* 面试。
  我进来也面试了好多同学，其实我一直认为，一场最完美的面试，就应该是
  interviewer和interviewee之间的博弈。特别聪明的较量，前期就是找一个博
  弈的方面，之后就应该是智力的博弈，可能是我现在身份的缘故，我一直没有
  看到可以和我直接博弈的同学。
  我很清楚我有很大的漏洞，但是博弈之时用不上力。
