# -*- mode: org -*-
# Last modified: <2013-03-17 12:07:51 Sunday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   Mother
#+AUTHOR: Richard Wong

* 母亲
  母亲都希望孩子过上好日子，我也明白，那作为母亲的这个个体，至少先是个
  女人，至少先是个人，因为孩子，丢弃了自己的生活，我和我妈也是相依为命
  十数载过来的，cc只是说，你没有我家人辛苦。但我也想说，你经历过什么？
  家人对于你又是什么？你知道爸妈如果相互心理出轨对孩子影响是什么么？至
  少你有一个非常幸福完美的家庭。
  这一点我非常感激我的母亲，我妈妈坚持给我一个完美的家庭，让我建立一个
  正确的社会观。

  之前，妈妈就跟我说，儿子诶，你到哪里去，妈妈就跟你到哪里去。我当时觉
  着非常好，每一个儿子都有一定的恋母情节把。
  但是，我现在在北京，刚刚一年，我觉着这非常不科学，因为跟cc的关系总是
  时疏时紧，这会让我非常纠结。可能每一对恋人都是这样？不过我妈妈来了，
  更不容易做自己，但是妈妈的格局我已经可以感觉到，已经被限制到邯郸了，
  我希望让我妈在付出最小代价的情况下，来到北京，感受一下生活，当然，邯
  郸也不是一个非常和谐的地方，烟雾弥漫，PM2.5一样超标，比北京还严重。
  至少北京经常刮大风，pm2.5可以吹到其他地方去。
  我知道邯郸是一个宣扬道德非常厉害的城市，但是邯郸一样也是一个装逼成风
  的城市，经济水平逐步提高，带来的是满城的堵车，基础建设一直跟不上来，
  倒是因为政府内购城中村产生了好多千万富翁。使得很多本地住户只希望与这
  些人联袂。这些人具备最高的生产力么？能代表邯郸未来的发展和希望么？这
  种人的生活态度能留下什么？无奈，因为这是一个经济社会，近年来发展市场
  经济一方面没有解决普通公民的个人资产意识，另一方面却造成了金钱至上的
  沦丧文化。
  所以我希望带我的家人先出去看看这个世界。
  我觉着接我妈过来肯定会遇到各种各样的困难，但是没办法，这些都能客服。
  这仅仅是开始，不能这么快忘本，对于我自己也是一种进步。不一定我妈就会
  烦我好多。真的。我需要把我妈接过来。（我觉着我很清楚这意味着什么）
  我还希望至少让我姥姥过来住一段时间。
  我能做什么？我只能更努力，磨练自己的态度，性格和能力。
