# -*- mode: org -*-
# Last modified: <2012-01-20 20:06:25 Friday by richard>
#+STARTUP: showall
#+TITLE:   2012plan

* 按照时间顺序：
1. 去深圳找一个外企（专业软件企业，不做外包企业的码农）就职。
   尽量找个最合适的工作，先是实习吧。我觉着我能力是有一定竞争力的，有
   技术，懂交流，工资就要个可以平常实习生得的就行了。能力有更合适得发
   展前景很重要。周围得人都是大牛就算了，国内也没指望都是大牛。但是至
   少用vim 或者emacs之类得Editor很重要，都是教育你用eclipse 或者IDE去
   写代码的企业。。。哥只能说——呵呵。
   现阶段，大致是希望在一个企业就职个一年或者1年半，以免学不到东西。
   （前三四个月允许以实习生得身份。）
   当然，如果企业足够好的话，钱什么都是浮云。能让我学到东西是关键。如
   果犀利到我足够满意，我愿意交钱干苦力。（太不孝顺了。霍霍。）
2. 给老爸买个好点得电动刮胡刀，给老妈买个电动牙刷。（如果有这个能力的话）
3. 骑车行走川藏线。（大概在暑期吧，实习合同换就职合同的时候）
4. 一定要找机会和企业的大boss聊聊天，学习一下上位者考虑的东西和方面。
5. Toefl需要重考，至少需要考105以上吧。（等到了深圳在报名吧。）

* 长期计划：
1. 出国申请很重要：
   我依然有我得出国梦。无论国内多么优越得待遇都不会阻止我更进一步得信
   心。（希望我就职得过程中，可以有experts，或者colleague可以给我写
   recommendation，我会努力工作，这也是我应得的。）
2. 英语依然还是一场战争：
   虽然现在已经保持只学习原版书已经有2年多得，读专业英语胡啦胡啦就过去
   了，不忌讳听和说大串大串的鸟文。但是还是有不少得缺点的。
   举例如下：
   1. 原版电影听不懂。
   2. 英语表达（无论口语还是写作）不够规范，错误众多。
3. 专业要更努力：
   最后一年因为准备GRE和Toefl考试耽误了不少专业的进度，本来说编译器就
   应该很早写出来得，这么简单得学术玩意墨迹到现在还在debug，实在令人伤
   不起。怎么都感觉自己是得了芝麻，丢了西瓜。还是自己得计划做的不好。
   （按计划，现在至少应该把emacs的python插件设计出来了。。。因为没有完
   成，不知到工作量，所以估计这个的吹嘘得成分估计很大。）
   因为很久没有用C++，elisp之类得玩意，忘得也差不多了。在我这准备考试得
   瞬间，C++就已经定义为专家级语言了，PC开始下坡了，android称霸市场了。
   nokia玩完了。为了自己不落后，我要更努力才行啊！！
   现在就想到这么多，之后得再说咯。。
