# -*- mode: org -*-
# Last modified: <2012-08-11 11:29:46 Saturday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   22岁谈坚持
#+AUTHOR: Richard Wong
Persistence in 22 years old.

写给我的朋友的心里话。

我今年22。非常2的一年。
陶喆曾经也22.

近来跟母亲谈了谈心。谈心总是有新体验。

来北京近半年，学到不少专业上的知识，这里就不说了，也学了不少生活上的东
西。

还是我那句话，我说的都是错的，每个人有每个人不同的生活体验，拥有不同程
度的偏见和奇妙的观点，你最好先假设我说的是错误的。别信我的。：）

我有一些学会计专业的朋友，忙忙碌碌的一天总是白驹过隙。我查了查，注册会
计师都已经考过了几十万了。[fn:1]
会计大概也是千万左右的这个标准，看到软件领域的健康发展，估计会计的数量
和变种会越来越多，但是精算师往往非常少，跟系统架构师一样。

跟会计类似，据说中国大陆程序员估计有了10M左右，如果除去边缘行业的，估
计也就百万左右。但是看能力来看，如果排到几十万的基本都已经水货的不像样
了。用一句话验证就是：请区分集成测试和单元测试的区别。有的人一看就有各
种想法，有的人根本没有这种观念，就是代码，写写写。
Mars有一个观点很有意思，我也很支持这种观点，依稀记得Joel Spolsky也说过
类似的话。

     *少写代码，多看代码。*

代码跟文章一样，多看才知道怎么写牛逼。最近我一般都很少动手写东西了，大
多数时间在看论文，看开源。

想起来之前看的精算师貌似很牛逼。但是难度大的不就是基础科目，让你懂数学，
经济学，又没有让你精通。何况这个世界有几个人能够精通一门学问？区区考试
而已，多少更牛的人士根本就没有去考。当然，我是行外人。。。：）

但是如计算机方面的，只有等级考试和程序员考试是大陆官方的考试。其他的都
很小众。基本都不是很管用。

不少非常要好的朋友就有人曾经给我说，上班是如何如何忙，如何如何烦躁，各
种折磨人的事情，你下班根本没有心思去做其他的事情。
我当时没有话语权，但是我现在只能说，坚持一下，你会做一天，再坚持一下，
你就又做一天，你看看电视，玩玩手机，墨迹墨迹，也是一天。到时候有你后悔
的，类似的人只能和类似的人生活在一起，如果你喜欢和优秀的人在一起，那你
必须变得优秀。
说一个夸张一点的总结上一代人的特点：
结婚前：
女生先觉着自己可以进步变得很牛逼，有魅力。可以吸引所有人。
然后发觉太辛苦了，觉着先找个男朋友一起进步比较重要。
男生则是觉着什么都可以等到之后再说，但是看到漂亮妞就不之后了。。。
结婚后：
女人是先望夫成龙，再望子成龙。
男人是先觉着可以成龙，然后觉着挺辛苦的，然后跟女人一起望子成龙吧。

不会被同样的错误击败的只有凤凰星座的圣斗士么。

即使你另外一半，也永远不要指望被人能够完成你的理想，你的理想只有你自己
能完成。

当然，我也22了，不是12了，热爱生活，希望自己健康，家人健康，生活幸福，
工作开心。
生活和代码毕竟是两个意思。工作再多也只是生活有机的一部分，关爱关爱老妈，
关爱关爱老爸，找个对象，伤伤心，开开心，挺好。但是一定不要做后悔的事情，
有些事情，只有自己知道。说句已经传到都恶心的话：“冷暖自知”，因为你冷你
暖，你自己才知道，
*别忘了关爱自己。*

作为一个立志成为科学家的人，先定义一下自己的意思：
1. 你本身的肉体。
2. 你自身的精神信念思想。

然后定义一下关爱的意思：
1. 对自己好，不去做困难的事情？
2. 天天在家里憋着上网？
3. 因为各种琐事困扰，不力求一点改变？
4. 不能学习，这样会死脑细胞？
我相信我说明白了。

时间太有限了，来北京，感觉没有一天事情能做完的。人总是要休息，休息也是
时间的消耗，并不是没有事情才休息，休息也是一件非常重要的事情。而且更重
要。

对于那些看本文不爽的：
这个文章首先是写给我朋友的，挚友的，不爽的留名，或者把我拉黑。
然后，我有个非常大的缺点，就是文章喜欢说成教条式的。
如果你认为我语言上自我优越感过强。真没有。与其批判我的优越感，不如想想
你自己的心态。为什么你会认为我的优越感会过强。是不是你太弱小了，不服
气？强大如狮子是不屑于跟小东西斗的。况且你也咬不到我。：）

* Footnotes

[fn:1] [[http://www.gov.cn/jrzg/2009-10/03/content_1432214.htm]]
