# -*- mode: org -*-
# Last modified: <2012-06-01 08:48:46 Friday by richard>
#+STARTUP: showall
#+TITLE:   信息检索
* 目的
  信息检索的起源于图书馆的资料查询和文摘索引工作。
  信息检索研究的目的是寻找从文档中获取可用信息的模型和算法。

  信息检索的传统问题是需要用户输入一个表述需求信息的查询字段，系统回复一个包含所需信息的文档列表，这一类问题成为特定信息的检索问题。
  这个问题主要存在两种模型。
1. 精确匹配模型。（布尔查询模型）
2. 文档相关匹配模型。（本次采用的）
   特点： 和查询信息相关度大的文档优先返回。

* 倒排索引inverted index
  倒排索引是这样一个数据结构，他列出了每个单词所在的所有文档，以及在每一篇文档中出现的频词，建立倒拍索引可以大大方便查询字段的查找，查询系统只需要在索引中找到该单词，就可以确认他的出现文档。
  一个优化的倒排索引也包含单词的位置信息，除了上面提到的信息外，在索引中还列出了单词在文档中的位置。这样利用包含位置信息的索引就可以查找短语字段，其中每个单词的位置用距离文档起始位置的偏移值来表示。含有单词位置信息的倒排索引文件为搜索短语提供了可能。
** 将出现次数大于25的二元结构都作为短语，虽然简单，但是效果却出奇的好。
** 寻找一套中文停用词。


* 评估方法
  准确率，召回率
  插值平均准确率11点。t统计。

* 文档概率排序准则。
  文档概率排序准则PRP。
  将文档按照相关概率的降需排列是最优的文档排序方法。


** 向量空间模型
   概念简单，应用方便，以及利用空间相似性来逼近语义相似性等优点。

* jargons
** posting
   如果某个特定的term索引了某个特定的document，那么称之为posting，说白了posting就是带position信息的term，在相关度检索中可能有一定的用途的。
** posting list.
   给定一个名为t的term，它索引着一个documents列表，这称之为t的posting list
** xapian 的存储方式
   在某些IR系统的内部是使用数字来表示term的，因此在这些系统中，term list则是数字组成的集合，而Xapian则不是这样，它使用原汁原味的term，而使用前缀来压缩存储空间。


