# -*- mode: org -*-
# Last modified: <2012-05-11 12:28:05 Friday by richard>
#+STARTUP: showall
#+TITLE:   停用词选取方案

方案主要有：[1]
1. 文档频数（ DF）
   DF是一种简单的评估函数，其值为训练集合中包含次单词的文本数，DF评估函数的理论假设是当一个词在大量文本中出现时,这个词通常被认为是噪声词。
2. 词频（WF）
   WF同样是一种简单的评估函数，其值为训练集合中次单词发生的词频数。WF
   评估函数的理论假设是当一个词在大量出现时，通常被人为是噪声词。
3. 熵计算 ( entropy calculation, EC)[3]
   熵计算是一个基于单词出现的平均信息量，对词的有效性进行计算。
   W(w)=1+1/(ln(n))\Sigma{p_i(w)ln[p_i(w)]}

4. 联合熵 ( union entropy, UE)
   基于词在句子中出现的频率与该词包含个icid句子频率的联合熵分别计算词
   条在语料库中各个句子内发生的概率，以及包含该词条的句子在文本中发生
   的概率P_j，计算他们的熵，并根据他们的联合熵选取停用词：
   当一个词在句子中出现的平均信息量和包含该词的句子的平均信息量较大时,
   表示该词较为普通.应用该方法可以有效避免语料选取不均衡造成的停用词选
   取错误.

其中，如果对停用词按照其出现的文本频数降序排序,用前10个停用词削减特征
向量空间,不会产生负面影响;用前100个停用词削减特征向量空间,所产生的负面
影响非常小.[2]

其中基于熵计算的选取方式更倾向于选取文本中稳定出现的词，因此更容易受到文本行文方式等的影响。用联合熵法选取的停用词更倾向于选取在句子中稳定出现且出现较多的词，因此受文本的行文方式影响较少，选取出的停用词更能反映文本的真实情况。[1]
而微博是一个更容易出现各类行文的场所，所以联合熵法将会更适用于微博的使用。

粒度选取为句。
可能需要通过句来处理问题。


主要的思路是将基本的停用词分为两类：
1. 基本的停用词。
   主要是标点。为必然的无法表达含义的停用词。
   这点很重要。在生成情感的时候，单个标点恐怕也能表现情感。这时候减少
   过滤就可以很容易的解决这个问题。
2. 自动生成停用词。
   通过各种处理得到自动生成的停用词词表，期间应该先去除了已经存储了的
   停用词以及不应该出现的有意义词。

   有一个基本的数据结构stopword类，存储停用词以及高频有意义词汇。



[1]:顾益军,樊孝忠,王建华,等.中文停用词表的自动选取[J].北京理工大学学报,2005,25(04):337—340.
[2]:Sinka M P, Corne D W. Web intelligence WI 2003
Proceedings IEEE/ WIC International Conf erence on Soc[C]. Los Alamitos, IEEE Comput ,
2003. 396-402.
[3]:Yang Y. Pedersen J O. A comparative study on
feature selection in text categorization[A].
ICML-97, 14th International
Morgan Kauf mann Publishers Inc. , 1997. 412-420.

