# -*- mode: org -*-
# Last modified: <2013-02-04 13:35:18 Monday by richard>
#+STARTUP: showall
#+LaTeX_CLASS: chinese-export
#+TODO: TODO(t) UNDERGOING(u) | DONE(d) CANCELED(c)
#+TITLE:   Where Is Your Tibet
#+AUTHOR: Richard Wong

---西藏是世界之脊。每个人都有自己的西藏。希望大家一定要抽出时间去一次。
有花堪折直须折，莫待无花空折枝。

* 准备
  毕业了，我想要的东西都离我很远，时不时会感觉非常烦躁。
  我是一个不够现实的人，几乎我的同学都这么说。
  所以我要去骑下来川藏线。
  期待着做一些真正nb的东西。或者，我期待一种突破。
  感觉我生活在笼子里面，如何才能高飞。
  每个人都有一个约束自己的盒子。
  我不知道什么是盒子，但是我知道我川藏线回来之后，我一定会突破这个盒子。
  在路上肯定会遇到各种各样的困难，只有你开始去做了，那就是一种突破。
  很担心路上的安全，是否会被泥石流埋住，是否会被抢劫，是否会被抛尸。

  但是我知道，这都还只是担心，在做之前，担心只会变得越来越多。何况已经有
  那么多人都去做，为什么我不可以？
  已经锻炼了很久了，从最基本的骑行姿势，踩踏技巧，还有修车技术。如果不去
  的话，这些又能算什么？
  干脆放下一切，出发吧。

* 路上遇到的困难
  没有热水，没有电，甚至在炉霍听到了枪声，但我知道这些都不是问题。
  路最烂的地方，是在映秀到卧龙的路上，你都几乎不能称之为路，到处是此处塌
  陷的标志，踏着水，踏着泥，踏着石子，上着坡，到了卧龙。比较幸运，准备
  充分，车胎没有爆掉。（扎不是问题，爆了很麻烦，因为我根本没有准备备用
  外胎）
  坏车子的地方，甘孜段，每骑行半个小时就要下自行车扣泥巴，泥巴是有很多种
  的，稀稀的，车子会甩一身泥，半粘稠的，很滑容易摔倒，非常粘稠的，我半个
  小时就要下来扣车轮子，要不就骑不动。
  就在那天，无论怎么调试，前圈只能用小轮了。

** 最困难
   其实最困难的不是雀儿山（川藏第一险），而是一个小地方，梁子疙瘩。
   在（丹巴到）八美的路上。
   （当时北线路上没有人骑车，不知道路况究竟如何）我记得昨天晚上跟碰到逆向
   骑行的人，聊天，他只是笑着说nb啊，我下来倒是挺爽的，你可就坑爹了。我可
   是一点都不像再爬上去
   也就在昨晚我唯一的队友（小龙）因为受伤离开。
   独自研究路段，3点钟睡觉，6点钟出发。（时区问题：相当于咱们这里的4点）
   转圈转过了不知多少圈之后，感觉自己真的要崩溃了。默默对自己说不要蹬了，
   随便再来一个车，就搭车走。
   但是看着路过的车缓缓爬过去车窗里面伸出的大拇指，我实在是不能。
   终于看到垭口的时候，下了雨，非常大，然后就是雷声，大块的冰雹。但是我不
   能放弃，更没法停止，继续骑，看了一眼手机，还有两个小时天黑，当然，我只
   有5公里的上坡。
   当时海拔大概有4.3K，喘喘的。雨水很快就过去，天晴了，旁边就是两圈彩虹。
   里面的雾是明亮的。真漂亮。
   到了垭口，我觉着心态变化非常之大，这世界上不会再有事情我会输，我知道
   我什么都可以做到，谢谢路边给我伸大拇指的人，谢谢对面给我说扎西德勒的人。
   下坡之后，很快就到了八美。

   从那之后我就明白一件事情：
   无论多么大的困难，什么样的遭遇，你需要做的只是精心准备，保持体力，早点
   睡觉，准时出发，然后坚持一下。真的什么都可以做的到。

   现在我感觉理想很近。这个世界很大，很美。
   我觉着别人说什么成功，什么故事，那都是别人的。对于你而言真实与否，都不
   属于你，做好自己。

* post art.
  川藏线，分为南北两条。川藏线如果走北线会遇到川藏第一险：雀儿山。
  在成都的时候我和dragon就很紧张，因为没有队友。
  后来和dragon商量，要走就走点牛逼的，川藏南线事实上已经被骑烂了。okok，
  那我们骑车走小北线吧，路过都江堰，走映秀穿卧龙，挑战巴狼山。
  虽然小龙最后没有全程骑下来，但是挑战的精神是足够的（也说明跟我一样幼稚:)）
  希望13年，就是即将到来的一年，我和dragon还有机会骑车子出去玩！
  问，dragon你的腿啥时候好啊。不锻炼整天鲁是没有希望的。

* To be continued.
  ruminations about tibet
